## Create  User
POST http://localhost:3110/users
Content-Type: application/json

{
    "Fname": "Sharon",
    "Lname":"Cherotich",
    "email": "sharoncherotich112@gmail.com",
    "phone_number": "123456789",
    "password": "123456789"
   
}

### Get all Users
GET http://localhost:3110/users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw

### Get One
GET http://localhost:3110/users/6ee1118f-e6ce-4a3e-bffc-1c89bb0f6d60
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw
### Update a user
PUT http://localhost:3110/users/update/0c286855-05d9-4b0d-8dcf-d83a0a6311ff
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0


{
    "Fname": "James43",
    "Lname":"Kariuki",
    "email": "jimna1@gmail.com",
    "phone_number": "0701036511",
    "password": "123456789"
}

### Delete a user

DELETE http://localhost:3110/users/delete/34ef96c4-5d98-4d6b-a1a2-2e42a1b10ae5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0
