## Create  User
POST http://localhost:3110/users
Content-Type: application/json

{
    "Fname": "Osai",
    "Lname":"bhai",
    "email": "osaibhai431@gmail.com",
    "phone_number": "05678899",
    "password": "123456789"
   
}

### Get all Users
GET http://localhost:3110/users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0

### Get One
GET http://localhost:3110/users/d7e22dbd-f955-46c3-9c2d-e9fd74f01cfd
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0
### Update a user
PUT http://localhost:3110/users/update/0c286855-05d9-4b0d-8dcf-d83a0a6311ff
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0


{
    "Fname": "James43",
    "Lname":"Kariuki",
    "email": "jimna1@gmail.com",
    "phone_number": "0701036511",
    "password": "123456789"
}

### Delete a user

DELETE http://localhost:3110/users/delete/d7e22dbd-f955-46c3-9c2d-e9fd74f01cfd
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0
