### login
POST http://localhost:3110/users/login
Content-Type: application/json

{
    "email": "devjameskw@gmail.com", 
    "password": "123456789"
   
}

### resetpwd
PUT http://localhost:3110/users/reset
Content-Type: application/json



{
   "email": "james.kariuki@thejitu.com", 
    "password": "123456789"
   
   
}
###Check details of the content

POST http://localhost:3110/users/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWM4NWQ4NzktOGUyMi00OWJmLWIwOTctM2RhM2FiMjQzN2I4IiwiZW1haWwiOiJqYW1lc2t3MjYwNUBnbWFpbC5jb20iLCJGbmFtZSI6IkphbWVzIiwicm9sZSI6InVzZXIiLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDkxOTgzNDQsImV4cCI6MTcwOTU0Mzk0NH0.76bwVKlYmpwHP4jCBtUi-3lYHXGqukfuQ6SdVR8jPAo