### login
POST http://localhost:3110/users/login
Content-Type: application/json

{
    "email": "osaibhai431@gmail.com", 
    "password": "123456789"
   
}

### resetpwd
PUT http://localhost:3110/users/reset
Content-Type: application/json



{
   "email": "james.kariuki@thejitu.com", 
    "password": "123456789"
   
   
}
###Check details of the content

POST http://localhost:3110/users/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDdlMjJkYmQtZjk1NS00NmMzLTljMmQtZTlmZDc0ZjAxY2ZkIiwiZW1haWwiOiJvc2FpYmhhaTQzMUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk1NTY4OTQsImV4cCI6MTcwOTkwMjQ5NH0.4b8p47EHC3_OfTBwVJb0RsCLZsmIAV9fWhqPfwK4wg0