## Create Order
POST http://localhost:3110/order
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw

{
    "cart_id": "19097e26-0bac-4b17-b6e5-18f6334a8df4",
    "user_id": "760136a6-5b7a-4688-9c33-c26518f123ad"
}

### Get a order by userid
GET http://localhost:3110/order/2deb31ed-d2d3-44f9-9412-d5119e9a59cd
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw


###Get All Orders

GET http://localhost:3110/order
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw


###CancelOrder

PUT http://localhost:3110/order/cancel/711f4bfe-f9c4-4ef5-ad6f-5e45d2ea7270
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw

###Change Status
PUT http://localhost:3110/order/changeStatus/711f4bfe-f9c4-4ef5-ad6f-5e45d2ea7270
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmRlYjMxZWQtZDJkMy00NGY5LTk0MTItZDUxMTllOWE1OWNkIiwiZW1haWwiOiJkZXZqYW1lc2t3QGdtYWlsLmNvbSIsIkZuYW1lIjoiSmFtZXMiLCJyb2xlIjoiYWRtaW4iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDk0OTMyNzQsImV4cCI6MTcwOTgzODg3NH0.hLvrILEbp1UgNTKjCjdrKHi-5bVbAZR9x6zmSO8VIIw