## Create  Product
POST http://localhost:3110/products
Content-Type: application/json

{
    "productname": "LG Frameless",
    "category_id":"893f6b6f-bbf9-4d92-a41d-2fb36fc6f019",
    "quantity": "23",
    "description": "Frameless Screen",
    "price": "99900",
    "image": "https://img.freepik.com/free-photo/landscape-nature-scene-tv-appliance-generative-ai_188544-12122.jpg?t=st=1709601368~exp=1709604968~hmac=3b81bea2200f2d54e178ac5f7e045c2cd52391e62e1a82e7e7cff9f4087bc87c&w=826"
}

### Get all Products
GET http://localhost:3110/products
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmVlMTExOGYtZTZjZS00YTNlLWJmZmMtMWM4OWJiMGY2ZDYwIiwiZW1haWwiOiJzaGFyb25jaGVyb3RpY2gxMTJAZ21haWwuY29tIiwiRm5hbWUiOiJTaGFyb24iLCJyb2xlIjoidXNlciIsImlzZGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcwOTkwMTg0NywiZXhwIjoxNzEwMjQ3NDQ3fQ.4hk3zYFPvgq4tXup2F0CL7wscdbWvFlywjy-bagQ418
### Get One
GET http://localhost:3110/products/4200c8e9-a428-4429-944f-9152119e9f15
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmVlMTExOGYtZTZjZS00YTNlLWJmZmMtMWM4OWJiMGY2ZDYwIiwiZW1haWwiOiJzaGFyb25jaGVyb3RpY2gxMTJAZ21haWwuY29tIiwiRm5hbWUiOiJTaGFyb24iLCJyb2xlIjoidXNlciIsImlzZGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcwOTkwMTg0NywiZXhwIjoxNzEwMjQ3NDQ3fQ.4hk3zYFPvgq4tXup2F0CL7wscdbWvFlywjy-bagQ418

### Get Products by Category Id
GET http://localhost:3110/products/prodbycategory/1908f955-f392-48ac-99eb-e6d6fc44a61c
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmVlMTExOGYtZTZjZS00YTNlLWJmZmMtMWM4OWJiMGY2ZDYwIiwiZW1haWwiOiJzaGFyb25jaGVyb3RpY2gxMTJAZ21haWwuY29tIiwiRm5hbWUiOiJTaGFyb24iLCJyb2xlIjoidXNlciIsImlzZGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcwOTkwMTg0NywiZXhwIjoxNzEwMjQ3NDQ3fQ.4hk3zYFPvgq4tXup2F0CL7wscdbWvFlywjy-bagQ418

### Update a Product
PUT http://localhost:3110/products/update/e169f80a-e94d-4b8d-a2e9-949dcf766c95
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmVlMTExOGYtZTZjZS00YTNlLWJmZmMtMWM4OWJiMGY2ZDYwIiwiZW1haWwiOiJzaGFyb25jaGVyb3RpY2gxMTJAZ21haWwuY29tIiwiRm5hbWUiOiJTaGFyb24iLCJyb2xlIjoidXNlciIsImlzZGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcwOTkwMTg0NywiZXhwIjoxNzEwMjQ3NDQ3fQ.4hk3zYFPvgq4tXup2F0CL7wscdbWvFlywjy-bagQ418


{
    "productname": "Synix Frameless",
    "category_id":"893f6b6f-bbf9-4d92-a41d-2fb36fc6f019",
    "quantity": "23",
    "description": "Frameless Screen",
    "price": "69900",
    "image": "https://img.freepik.com/free-photo/landscape-nature-scene-tv-appliance-generative-ai_188544-12122.jpg?t=st=1709601368~exp=1709604968~hmac=3b81bea2200f2d54e178ac5f7e045c2cd52391e62e1a82e7e7cff9f4087bc87c&w=826"
}

### Delete a Product

DELETE http://localhost:3110/products/delete/b9b1595d-0835-45fb-bb4f-e9412e78100a
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMGMyODY4NTUtMDVkOS00YjBkLThkY2YtZDgzYTBhNjMxMWZmIiwiZW1haWwiOiJqaW1uYUBnbWFpbC5jb20iLCJpc2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MDkxMjA3MTIsImV4cCI6MTcwOTQ2NjMxMn0.MuW9er349iQ04ju4nspottdVQuPsisS5Jqdb1Fuzqik
